### ISSUE TITLE
natty doesn't work with jpype 0.7.0 onwards

### ISSUE THREAD

**Issue by maxdh** [eadmundo/python-natty#3]
I only recently discovered natty and I think its great! Sadly as this module doesn't seem to be supported anymore I'm writing this more just a comment in case anyone else comes across natty and has the same issues getting it working that I did.

The most recent version of jpype is incompatible with natty and gives the following error:
```AttributeError: 'com.joestelmach.natty.DateGroup' object has no attribute 'dates'```

However it works fine if you specifically install jpype 0.6.3 (or earlier)

**Comment by Thrameos** [comment]
There appears to be a few things out of date with this package.

In particular,
- Accessing methods as fields was through the deprecated "beans" package.   Simply changing the accesses to use "getDates" instead would correct that issue.
- Automatic string conversion is no longer the default so some of the calls require some conversion `str()` in places.
- Attaching a thread manually is likely to lead to shutdown issues and has been deprecated since 0.7.0.  In Java shutdown is not performed until the last non-deamon thread is closed.  So the attachThreadToJVM is likely going to cause a freeze on exit unless there is thread clean up routines.
